.\"-*- nroff -*-
.TH TRITIUM 1 "June  1, 2007"
.SH NAME
tritium \- a tabbed/tiling window manager for the X Window System
.SH SYNOPSIS
.B tritium
.RI [ options ]
.SH DESCRIPTION
.B tritium
is a tabbed / tiling window manager geared towards keyboard users.
.SH OPTIONS
.B \-c, \-\config-file filename
use
.RI filename
as the tritium config file.
.SH AUTHOR
tritium was written by Mike O'Connor <stew@vireo.org>
